// UFC Title Lineage Dataset (v2 — exhaustive defenses)
// Source: Wikipedia "List of UFC champions" full title-history tables per division, cross-checked
// against known UFC records for interim/vacancy edge cases. Fetched/rebuilt 2026-07-14.
// type: "change" = title changed hands, "defense" = successful title defense,
//       "interim" = interim title fight, "draw" = draw/no-contest that retained the title, "promoted" = promoted without a fight
// This revision replaces v1, which under-counted defenses for long-reigning champions (e.g. Jon Jones,
// Anderson Silva, Demetrious Johnson, José Aldo, GSP, Amanda Nunes) because the first source page
// truncated its "Defenses" column after 1-2 entries per reign.
// v3 (2026-07-15): added UFC Freedom 250 "UFC White House" card (Jun 14, 2026) — Justin Gaethje def.
// Ilia Topuria for the undisputed Lightweight title, and Ciryl Gane def. Alex Pereira for the vacant
// interim Heavyweight title.
// v4 (2026-08-15): added all title fights from UFC 324 through UFC 328 — Kayla Harrison def. Amanda
// Nunes (W. Bantamweight defense, UFC 324), Charles Oliveira def. Max Holloway (BMF title, UFC 326),
// Carlos Ulberg def. Jiří Procházka (vacant Light Heavyweight title, UFC 327), Sean Strickland def.
// Khamzat Chimaev (Middleweight title, UFC 328), Joshua Van def. Tatsuro Taira (Flyweight defense,
// UFC 328). Note: tonight's actual event is UFC 330 (Makhachev vs. Ian Machado Garry for Welterweight,
// Dern vs. Gillian Robertson for Women's Strawweight) — not yet contested at time of writing, so not
// included. UFC 331 (Van vs. Pantoja rematch) is scheduled for Sep 19, 2026.

const FIGHTS = [
// ===== HEAVYWEIGHT =====
{division:"Heavyweight", date:"1997-02-07", event:"UFC 12", winner:"Mark Coleman", loser:"Dan Severn", type:"change"},
{division:"Heavyweight", date:"1997-07-27", event:"UFC 14", winner:"Maurice Smith", loser:"Mark Coleman", type:"change"},
{division:"Heavyweight", date:"1997-10-17", event:"UFC 15", winner:"Maurice Smith", loser:"Tank Abbott", type:"defense"},
{division:"Heavyweight", date:"1997-12-21", event:"UFC Japan", winner:"Randy Couture", loser:"Maurice Smith", type:"change"},
{division:"Heavyweight", date:"1999-05-07", event:"UFC 20", winner:"Bas Rutten", loser:"Kevin Randleman", type:"change"},
{division:"Heavyweight", date:"1999-11-19", event:"UFC 23", winner:"Kevin Randleman", loser:"Pete Williams", type:"change"},
{division:"Heavyweight", date:"2000-06-09", event:"UFC 26", winner:"Kevin Randleman", loser:"Pedro Rizzo", type:"defense"},
{division:"Heavyweight", date:"2000-11-17", event:"UFC 28", winner:"Randy Couture", loser:"Kevin Randleman", type:"change"},
{division:"Heavyweight", date:"2001-05-04", event:"UFC 31", winner:"Randy Couture", loser:"Pedro Rizzo", type:"defense"},
{division:"Heavyweight", date:"2001-11-02", event:"UFC 34", winner:"Randy Couture", loser:"Pedro Rizzo", type:"defense"},
{division:"Heavyweight", date:"2002-03-22", event:"UFC 36", winner:"Josh Barnett", loser:"Randy Couture", type:"change"},
{division:"Heavyweight", date:"2002-09-27", event:"UFC 39", winner:"Ricco Rodriguez", loser:"Randy Couture", type:"change"},
{division:"Heavyweight", date:"2003-02-28", event:"UFC 41", winner:"Tim Sylvia", loser:"Ricco Rodriguez", type:"change"},
{division:"Heavyweight", date:"2003-09-26", event:"UFC 44", winner:"Tim Sylvia", loser:"Gan McGee", type:"defense"},
{division:"Heavyweight", date:"2004-06-19", event:"UFC 48", winner:"Frank Mir", loser:"Tim Sylvia", type:"change"},
{division:"Heavyweight", date:"2005-02-05", event:"UFC 51", winner:"Andrei Arlovski", loser:"Tim Sylvia", type:"interim"},
{division:"Heavyweight", date:"2005-06-04", event:"UFC 53", winner:"Andrei Arlovski", loser:"Justin Eilers", type:"defense"},
{division:"Heavyweight", date:"2005-08-12", event:"—", winner:"Andrei Arlovski", loser:"Frank Mir", type:"promoted"},
{division:"Heavyweight", date:"2005-10-07", event:"UFC 55", winner:"Andrei Arlovski", loser:"Paul Buentello", type:"defense"},
{division:"Heavyweight", date:"2006-04-15", event:"UFC 59", winner:"Tim Sylvia", loser:"Andrei Arlovski", type:"change"},
{division:"Heavyweight", date:"2006-07-08", event:"UFC 61", winner:"Tim Sylvia", loser:"Andrei Arlovski", type:"defense"},
{division:"Heavyweight", date:"2006-11-18", event:"UFC 65", winner:"Tim Sylvia", loser:"Jeff Monson", type:"defense"},
{division:"Heavyweight", date:"2007-03-03", event:"UFC 68", winner:"Randy Couture", loser:"Tim Sylvia", type:"change"},
{division:"Heavyweight", date:"2007-08-25", event:"UFC 74", winner:"Randy Couture", loser:"Gabriel Gonzaga", type:"defense"},
{division:"Heavyweight", date:"2008-02-02", event:"UFC 81", winner:"Antônio Rodrigo Nogueira", loser:"Tim Sylvia", type:"interim"},
{division:"Heavyweight", date:"2008-11-15", event:"UFC 91", winner:"Brock Lesnar", loser:"Randy Couture", type:"change"},
{division:"Heavyweight", date:"2008-12-27", event:"UFC 92", winner:"Frank Mir", loser:"Antônio Rodrigo Nogueira", type:"interim"},
{division:"Heavyweight", date:"2009-07-11", event:"UFC 100", winner:"Brock Lesnar", loser:"Frank Mir", type:"defense"},
{division:"Heavyweight", date:"2010-03-27", event:"UFC 111", winner:"Shane Carwin", loser:"Frank Mir", type:"interim"},
{division:"Heavyweight", date:"2010-07-03", event:"UFC 116", winner:"Brock Lesnar", loser:"Shane Carwin", type:"defense"},
{division:"Heavyweight", date:"2010-10-23", event:"UFC 121", winner:"Cain Velasquez", loser:"Brock Lesnar", type:"change"},
{division:"Heavyweight", date:"2011-11-12", event:"UFC on Fox: Velasquez vs. dos Santos", winner:"Junior dos Santos", loser:"Cain Velasquez", type:"change"},
{division:"Heavyweight", date:"2012-05-26", event:"UFC 146", winner:"Junior dos Santos", loser:"Frank Mir", type:"defense"},
{division:"Heavyweight", date:"2012-12-29", event:"UFC 155", winner:"Cain Velasquez", loser:"Junior dos Santos", type:"change"},
{division:"Heavyweight", date:"2013-05-25", event:"UFC 160", winner:"Cain Velasquez", loser:"Antônio Silva", type:"defense"},
{division:"Heavyweight", date:"2013-10-19", event:"UFC 166", winner:"Cain Velasquez", loser:"Junior dos Santos", type:"defense"},
{division:"Heavyweight", date:"2014-11-15", event:"UFC 180", winner:"Fabrício Werdum", loser:"Mark Hunt", type:"interim"},
{division:"Heavyweight", date:"2015-06-13", event:"UFC 188", winner:"Fabrício Werdum", loser:"Cain Velasquez", type:"change"},
{division:"Heavyweight", date:"2016-05-14", event:"UFC 198", winner:"Stipe Miocic", loser:"Fabrício Werdum", type:"change"},
{division:"Heavyweight", date:"2016-09-10", event:"UFC 203", winner:"Stipe Miocic", loser:"Alistair Overeem", type:"defense"},
{division:"Heavyweight", date:"2017-05-13", event:"UFC 211", winner:"Stipe Miocic", loser:"Junior dos Santos", type:"defense"},
{division:"Heavyweight", date:"2018-01-20", event:"UFC 220", winner:"Stipe Miocic", loser:"Francis Ngannou", type:"defense"},
{division:"Heavyweight", date:"2018-07-07", event:"UFC 226", winner:"Daniel Cormier", loser:"Stipe Miocic", type:"change"},
{division:"Heavyweight", date:"2018-11-03", event:"UFC 230", winner:"Daniel Cormier", loser:"Derrick Lewis", type:"defense"},
{division:"Heavyweight", date:"2019-08-17", event:"UFC 241", winner:"Stipe Miocic", loser:"Daniel Cormier", type:"change"},
{division:"Heavyweight", date:"2020-08-15", event:"UFC 252", winner:"Stipe Miocic", loser:"Daniel Cormier", type:"defense"},
{division:"Heavyweight", date:"2021-03-27", event:"UFC 260", winner:"Francis Ngannou", loser:"Stipe Miocic", type:"change"},
{division:"Heavyweight", date:"2021-08-07", event:"UFC 265", winner:"Ciryl Gane", loser:"Derrick Lewis", type:"interim"},
{division:"Heavyweight", date:"2022-01-22", event:"UFC 270", winner:"Francis Ngannou", loser:"Ciryl Gane", type:"defense"},
{division:"Heavyweight", date:"2023-03-04", event:"UFC 285", winner:"Jon Jones", loser:"Ciryl Gane", type:"change"},
{division:"Heavyweight", date:"2023-11-11", event:"UFC 295", winner:"Tom Aspinall", loser:"Sergei Pavlovich", type:"interim"},
{division:"Heavyweight", date:"2024-07-27", event:"UFC 304", winner:"Tom Aspinall", loser:"Curtis Blaydes", type:"defense"},
{division:"Heavyweight", date:"2024-11-16", event:"UFC 309", winner:"Jon Jones", loser:"Stipe Miocic", type:"defense"},
{division:"Heavyweight", date:"2025-06-21", event:"—", winner:"Tom Aspinall", loser:"Jon Jones", type:"promoted"},
{division:"Heavyweight", date:"2026-06-14", event:"UFC Freedom 250 (White House)", winner:"Ciryl Gane", loser:"Alex Pereira", type:"interim"},

// ===== LIGHT HEAVYWEIGHT =====
{division:"Light Heavyweight", date:"1997-12-21", event:"UFC Japan", winner:"Frank Shamrock", loser:"Kevin Jackson", type:"change"},
{division:"Light Heavyweight", date:"1998-03-13", event:"UFC 16", winner:"Frank Shamrock", loser:"Igor Zinoviev", type:"defense"},
{division:"Light Heavyweight", date:"1998-05-15", event:"UFC 17", winner:"Frank Shamrock", loser:"Jeremy Horn", type:"defense"},
{division:"Light Heavyweight", date:"1998-10-16", event:"UFC Brazil", winner:"Frank Shamrock", loser:"John Lober", type:"defense"},
{division:"Light Heavyweight", date:"1999-09-24", event:"UFC 22", winner:"Frank Shamrock", loser:"Tito Ortiz", type:"defense"},
{division:"Light Heavyweight", date:"2000-04-14", event:"UFC 25", winner:"Tito Ortiz", loser:"Wanderlei Silva", type:"change"},
{division:"Light Heavyweight", date:"2000-12-16", event:"UFC 29", winner:"Tito Ortiz", loser:"Yuki Kondo", type:"defense"},
{division:"Light Heavyweight", date:"2001-02-23", event:"UFC 30", winner:"Tito Ortiz", loser:"Evan Tanner", type:"defense"},
{division:"Light Heavyweight", date:"2001-06-29", event:"UFC 32", winner:"Tito Ortiz", loser:"Elvis Sinosic", type:"defense"},
{division:"Light Heavyweight", date:"2001-09-28", event:"UFC 33", winner:"Tito Ortiz", loser:"Vladimir Matyushenko", type:"defense"},
{division:"Light Heavyweight", date:"2002-11-22", event:"UFC 40", winner:"Tito Ortiz", loser:"Ken Shamrock", type:"defense"},
{division:"Light Heavyweight", date:"2003-06-06", event:"UFC 43", winner:"Randy Couture", loser:"Chuck Liddell", type:"interim"},
{division:"Light Heavyweight", date:"2003-09-26", event:"UFC 44", winner:"Randy Couture", loser:"Tito Ortiz", type:"change"},
{division:"Light Heavyweight", date:"2004-01-31", event:"UFC 46", winner:"Vitor Belfort", loser:"Randy Couture", type:"change"},
{division:"Light Heavyweight", date:"2004-08-21", event:"UFC 49", winner:"Randy Couture", loser:"Vitor Belfort", type:"change"},
{division:"Light Heavyweight", date:"2005-04-16", event:"UFC 52", winner:"Chuck Liddell", loser:"Randy Couture", type:"change"},
{division:"Light Heavyweight", date:"2005-08-20", event:"UFC 54", winner:"Chuck Liddell", loser:"Jeremy Horn", type:"defense"},
{division:"Light Heavyweight", date:"2006-02-04", event:"UFC 57", winner:"Chuck Liddell", loser:"Randy Couture", type:"defense"},
{division:"Light Heavyweight", date:"2006-08-26", event:"UFC 62", winner:"Chuck Liddell", loser:"Renato Sobral", type:"defense"},
{division:"Light Heavyweight", date:"2006-12-30", event:"UFC 66", winner:"Chuck Liddell", loser:"Tito Ortiz", type:"defense"},
{division:"Light Heavyweight", date:"2007-05-26", event:"UFC 71", winner:"Quinton Jackson", loser:"Chuck Liddell", type:"change"},
{division:"Light Heavyweight", date:"2007-09-08", event:"UFC 75", winner:"Quinton Jackson", loser:"Dan Henderson", type:"defense"},
{division:"Light Heavyweight", date:"2008-07-05", event:"UFC 86", winner:"Forrest Griffin", loser:"Quinton Jackson", type:"change"},
{division:"Light Heavyweight", date:"2008-12-27", event:"UFC 92", winner:"Rashad Evans", loser:"Forrest Griffin", type:"change"},
{division:"Light Heavyweight", date:"2009-05-23", event:"UFC 98", winner:"Lyoto Machida", loser:"Rashad Evans", type:"change"},
{division:"Light Heavyweight", date:"2009-10-24", event:"UFC 104", winner:"Lyoto Machida", loser:"Maurício Rua", type:"defense"},
{division:"Light Heavyweight", date:"2010-05-08", event:"UFC 113", winner:"Maurício Rua", loser:"Lyoto Machida", type:"change"},
{division:"Light Heavyweight", date:"2011-03-19", event:"UFC 128", winner:"Jon Jones", loser:"Maurício Rua", type:"change"},
{division:"Light Heavyweight", date:"2011-09-24", event:"UFC 135", winner:"Jon Jones", loser:"Quinton Jackson", type:"defense"},
{division:"Light Heavyweight", date:"2011-12-10", event:"UFC 140", winner:"Jon Jones", loser:"Lyoto Machida", type:"defense"},
{division:"Light Heavyweight", date:"2012-04-21", event:"UFC 145", winner:"Jon Jones", loser:"Rashad Evans", type:"defense"},
{division:"Light Heavyweight", date:"2012-09-22", event:"UFC 152", winner:"Jon Jones", loser:"Vitor Belfort", type:"defense"},
{division:"Light Heavyweight", date:"2013-04-27", event:"UFC 159", winner:"Jon Jones", loser:"Chael Sonnen", type:"defense"},
{division:"Light Heavyweight", date:"2013-09-21", event:"UFC 165", winner:"Jon Jones", loser:"Alexander Gustafsson", type:"defense"},
{division:"Light Heavyweight", date:"2014-04-26", event:"UFC 172", winner:"Jon Jones", loser:"Glover Teixeira", type:"defense"},
{division:"Light Heavyweight", date:"2015-01-03", event:"UFC 182", winner:"Jon Jones", loser:"Daniel Cormier", type:"defense"},
{division:"Light Heavyweight", date:"2015-05-23", event:"UFC 187", winner:"Daniel Cormier", loser:"Anthony Johnson", type:"change"},
{division:"Light Heavyweight", date:"2015-10-03", event:"UFC 192", winner:"Daniel Cormier", loser:"Alexander Gustafsson", type:"defense"},
{division:"Light Heavyweight", date:"2016-04-23", event:"UFC 197", winner:"Jon Jones", loser:"Ovince Saint Preux", type:"interim"},
{division:"Light Heavyweight", date:"2017-04-08", event:"UFC 210", winner:"Daniel Cormier", loser:"Anthony Johnson", type:"defense"},
{division:"Light Heavyweight", date:"2018-01-20", event:"UFC 220", winner:"Daniel Cormier", loser:"Volkan Oezdemir", type:"defense"},
{division:"Light Heavyweight", date:"2018-12-29", event:"UFC 232", winner:"Jon Jones", loser:"Alexander Gustafsson", type:"change"},
{division:"Light Heavyweight", date:"2019-03-02", event:"UFC 235", winner:"Jon Jones", loser:"Anthony Smith", type:"defense"},
{division:"Light Heavyweight", date:"2019-07-06", event:"UFC 239", winner:"Jon Jones", loser:"Thiago Santos", type:"defense"},
{division:"Light Heavyweight", date:"2020-02-08", event:"UFC 247", winner:"Jon Jones", loser:"Dominick Reyes", type:"defense"},
{division:"Light Heavyweight", date:"2020-09-27", event:"UFC 253", winner:"Jan Błachowicz", loser:"Dominick Reyes", type:"change"},
{division:"Light Heavyweight", date:"2021-03-06", event:"UFC 259", winner:"Jan Błachowicz", loser:"Israel Adesanya", type:"defense"},
{division:"Light Heavyweight", date:"2021-10-30", event:"UFC 267", winner:"Glover Teixeira", loser:"Jan Błachowicz", type:"change"},
{division:"Light Heavyweight", date:"2022-06-12", event:"UFC 275", winner:"Jiří Procházka", loser:"Glover Teixeira", type:"change"},
{division:"Light Heavyweight", date:"2022-12-10", event:"UFC 282", winner:"Jan Błachowicz", loser:"Magomed Ankalaev", type:"draw"},
{division:"Light Heavyweight", date:"2023-01-21", event:"UFC 283", winner:"Jamahal Hill", loser:"Glover Teixeira", type:"change"},
{division:"Light Heavyweight", date:"2023-11-11", event:"UFC 295", winner:"Alex Pereira", loser:"Jiří Procházka", type:"change"},
{division:"Light Heavyweight", date:"2024-04-13", event:"UFC 300", winner:"Alex Pereira", loser:"Jamahal Hill", type:"defense"},
{division:"Light Heavyweight", date:"2024-06-29", event:"UFC 303", winner:"Alex Pereira", loser:"Jiří Procházka", type:"defense"},
{division:"Light Heavyweight", date:"2024-10-05", event:"UFC 307", winner:"Alex Pereira", loser:"Khalil Rountree Jr.", type:"defense"},
{division:"Light Heavyweight", date:"2025-03-08", event:"UFC 313", winner:"Magomed Ankalaev", loser:"Alex Pereira", type:"change"},
{division:"Light Heavyweight", date:"2025-10-04", event:"UFC 320", winner:"Alex Pereira", loser:"Magomed Ankalaev", type:"change"},
{division:"Light Heavyweight", date:"2026-04-11", event:"UFC 327", winner:"Carlos Ulberg", loser:"Jiří Procházka", type:"change"},

// ===== MIDDLEWEIGHT =====
{division:"Middleweight", date:"2001-09-28", event:"UFC 33", winner:"Dave Menne", loser:"Gil Castillo", type:"change"},
{division:"Middleweight", date:"2002-01-11", event:"UFC 35", winner:"Murilo Bustamante", loser:"Dave Menne", type:"change"},
{division:"Middleweight", date:"2002-05-10", event:"UFC 37", winner:"Murilo Bustamante", loser:"Matt Lindland", type:"defense"},
{division:"Middleweight", date:"2005-02-05", event:"UFC 51", winner:"Evan Tanner", loser:"David Terrell", type:"change"},
{division:"Middleweight", date:"2005-06-04", event:"UFC 53", winner:"Rich Franklin", loser:"Evan Tanner", type:"change"},
{division:"Middleweight", date:"2005-11-19", event:"UFC 56", winner:"Rich Franklin", loser:"Nate Quarry", type:"defense"},
{division:"Middleweight", date:"2006-03-04", event:"UFC 58", winner:"Rich Franklin", loser:"David Loiseau", type:"defense"},
{division:"Middleweight", date:"2006-10-14", event:"UFC 64", winner:"Anderson Silva", loser:"Rich Franklin", type:"change"},
{division:"Middleweight", date:"2007-07-07", event:"UFC 73", winner:"Anderson Silva", loser:"Nate Marquardt", type:"defense"},
{division:"Middleweight", date:"2007-10-20", event:"UFC 77", winner:"Anderson Silva", loser:"Rich Franklin", type:"defense"},
{division:"Middleweight", date:"2008-03-01", event:"UFC 82", winner:"Anderson Silva", loser:"Dan Henderson", type:"defense"},
{division:"Middleweight", date:"2008-10-25", event:"UFC 90", winner:"Anderson Silva", loser:"Patrick Côté", type:"defense"},
{division:"Middleweight", date:"2009-04-18", event:"UFC 97", winner:"Anderson Silva", loser:"Thales Leites", type:"defense"},
{division:"Middleweight", date:"2010-04-10", event:"UFC 112", winner:"Anderson Silva", loser:"Demian Maia", type:"defense"},
{division:"Middleweight", date:"2010-08-07", event:"UFC 117", winner:"Anderson Silva", loser:"Chael Sonnen", type:"defense"},
{division:"Middleweight", date:"2011-02-05", event:"UFC 126", winner:"Anderson Silva", loser:"Vitor Belfort", type:"defense"},
{division:"Middleweight", date:"2011-08-27", event:"UFC 134", winner:"Anderson Silva", loser:"Yushin Okami", type:"defense"},
{division:"Middleweight", date:"2012-07-07", event:"UFC 148", winner:"Anderson Silva", loser:"Chael Sonnen", type:"defense"},
{division:"Middleweight", date:"2013-07-06", event:"UFC 162", winner:"Chris Weidman", loser:"Anderson Silva", type:"change"},
{division:"Middleweight", date:"2013-12-28", event:"UFC 168", winner:"Chris Weidman", loser:"Anderson Silva", type:"defense"},
{division:"Middleweight", date:"2014-07-05", event:"UFC 175", winner:"Chris Weidman", loser:"Lyoto Machida", type:"defense"},
{division:"Middleweight", date:"2015-05-23", event:"UFC 187", winner:"Chris Weidman", loser:"Vitor Belfort", type:"defense"},
{division:"Middleweight", date:"2015-12-12", event:"UFC 194", winner:"Luke Rockhold", loser:"Chris Weidman", type:"change"},
{division:"Middleweight", date:"2016-06-04", event:"UFC 199", winner:"Michael Bisping", loser:"Luke Rockhold", type:"change"},
{division:"Middleweight", date:"2016-10-08", event:"UFC 204", winner:"Michael Bisping", loser:"Dan Henderson", type:"defense"},
{division:"Middleweight", date:"2017-07-08", event:"UFC 213", winner:"Robert Whittaker", loser:"Yoel Romero", type:"interim"},
{division:"Middleweight", date:"2017-11-04", event:"UFC 217", winner:"Georges St-Pierre", loser:"Michael Bisping", type:"change"},
{division:"Middleweight", date:"2017-12-07", event:"—", winner:"Robert Whittaker", loser:"Georges St-Pierre", type:"promoted"},
{division:"Middleweight", date:"2019-04-13", event:"UFC 236", winner:"Israel Adesanya", loser:"Kelvin Gastelum", type:"interim"},
{division:"Middleweight", date:"2019-10-06", event:"UFC 243", winner:"Israel Adesanya", loser:"Robert Whittaker", type:"change"},
{division:"Middleweight", date:"2020-03-07", event:"UFC 248", winner:"Israel Adesanya", loser:"Yoel Romero", type:"defense"},
{division:"Middleweight", date:"2020-09-26", event:"UFC 253", winner:"Israel Adesanya", loser:"Paulo Costa", type:"defense"},
{division:"Middleweight", date:"2021-06-12", event:"UFC 263", winner:"Israel Adesanya", loser:"Marvin Vettori", type:"defense"},
{division:"Middleweight", date:"2022-02-12", event:"UFC 271", winner:"Israel Adesanya", loser:"Robert Whittaker", type:"defense"},
{division:"Middleweight", date:"2022-07-02", event:"UFC 276", winner:"Israel Adesanya", loser:"Jared Cannonier", type:"defense"},
{division:"Middleweight", date:"2022-11-12", event:"UFC 281", winner:"Alex Pereira", loser:"Israel Adesanya", type:"change"},
{division:"Middleweight", date:"2023-04-08", event:"UFC 287", winner:"Israel Adesanya", loser:"Alex Pereira", type:"change"},
{division:"Middleweight", date:"2023-09-10", event:"UFC 293", winner:"Sean Strickland", loser:"Israel Adesanya", type:"change"},
{division:"Middleweight", date:"2024-01-20", event:"UFC 297", winner:"Dricus du Plessis", loser:"Sean Strickland", type:"change"},
{division:"Middleweight", date:"2024-08-18", event:"UFC 305", winner:"Dricus du Plessis", loser:"Israel Adesanya", type:"defense"},
{division:"Middleweight", date:"2025-02-09", event:"UFC 312", winner:"Dricus du Plessis", loser:"Sean Strickland", type:"defense"},
{division:"Middleweight", date:"2025-08-16", event:"UFC 319", winner:"Khamzat Chimaev", loser:"Dricus du Plessis", type:"change"},
{division:"Middleweight", date:"2026-05-09", event:"UFC 328", winner:"Sean Strickland", loser:"Khamzat Chimaev", type:"change"},

// ===== WELTERWEIGHT =====
{division:"Welterweight", date:"1998-10-16", event:"UFC Brazil", winner:"Pat Miletich", loser:"Mikey Burnett", type:"change"},
{division:"Welterweight", date:"1999-01-08", event:"UFC 18", winner:"Pat Miletich", loser:"Jorge Patino", type:"defense"},
{division:"Welterweight", date:"1999-07-16", event:"UFC 21", winner:"Pat Miletich", loser:"André Pederneiras", type:"defense"},
{division:"Welterweight", date:"2000-06-09", event:"UFC 26", winner:"Pat Miletich", loser:"John Alessio", type:"defense"},
{division:"Welterweight", date:"2000-12-16", event:"UFC 29", winner:"Pat Miletich", loser:"Kenichi Yamamoto", type:"defense"},
{division:"Welterweight", date:"2001-05-04", event:"UFC 31", winner:"Carlos Newton", loser:"Pat Miletich", type:"change"},
{division:"Welterweight", date:"2001-11-02", event:"UFC 34", winner:"Matt Hughes", loser:"Carlos Newton", type:"change"},
{division:"Welterweight", date:"2002-03-22", event:"UFC 36", winner:"Matt Hughes", loser:"Hayato Sakurai", type:"defense"},
{division:"Welterweight", date:"2002-07-13", event:"UFC 38", winner:"Matt Hughes", loser:"Carlos Newton", type:"defense"},
{division:"Welterweight", date:"2002-11-22", event:"UFC 40", winner:"Matt Hughes", loser:"Gil Castillo", type:"defense"},
{division:"Welterweight", date:"2003-04-25", event:"UFC 42", winner:"Matt Hughes", loser:"Sean Sherk", type:"defense"},
{division:"Welterweight", date:"2003-11-21", event:"UFC 45", winner:"Matt Hughes", loser:"Frank Trigg", type:"defense"},
{division:"Welterweight", date:"2004-01-31", event:"UFC 46", winner:"B.J. Penn", loser:"Matt Hughes", type:"change"},
{division:"Welterweight", date:"2004-10-22", event:"UFC 50", winner:"Matt Hughes", loser:"Georges St-Pierre", type:"change"},
{division:"Welterweight", date:"2005-04-16", event:"UFC 52", winner:"Matt Hughes", loser:"Frank Trigg", type:"defense"},
{division:"Welterweight", date:"2006-09-23", event:"UFC 63", winner:"Matt Hughes", loser:"B.J. Penn", type:"defense"},
{division:"Welterweight", date:"2006-11-18", event:"UFC 65", winner:"Georges St-Pierre", loser:"Matt Hughes", type:"change"},
{division:"Welterweight", date:"2007-04-07", event:"UFC 69", winner:"Matt Serra", loser:"Georges St-Pierre", type:"change"},
{division:"Welterweight", date:"2007-12-29", event:"UFC 79", winner:"Georges St-Pierre", loser:"Matt Hughes", type:"interim"},
{division:"Welterweight", date:"2008-04-19", event:"UFC 83", winner:"Georges St-Pierre", loser:"Matt Serra", type:"change"},
{division:"Welterweight", date:"2008-08-09", event:"UFC 87", winner:"Georges St-Pierre", loser:"Jon Fitch", type:"defense"},
{division:"Welterweight", date:"2009-01-31", event:"UFC 94", winner:"Georges St-Pierre", loser:"B.J. Penn", type:"defense"},
{division:"Welterweight", date:"2009-07-11", event:"UFC 100", winner:"Georges St-Pierre", loser:"Thiago Alves", type:"defense"},
{division:"Welterweight", date:"2010-03-27", event:"UFC 111", winner:"Georges St-Pierre", loser:"Dan Hardy", type:"defense"},
{division:"Welterweight", date:"2010-12-11", event:"UFC 124", winner:"Georges St-Pierre", loser:"Josh Koscheck", type:"defense"},
{division:"Welterweight", date:"2011-04-30", event:"UFC 129", winner:"Georges St-Pierre", loser:"Jake Shields", type:"defense"},
{division:"Welterweight", date:"2012-02-04", event:"UFC 143", winner:"Carlos Condit", loser:"Nick Diaz", type:"interim"},
{division:"Welterweight", date:"2012-11-17", event:"UFC 154", winner:"Georges St-Pierre", loser:"Carlos Condit", type:"defense"},
{division:"Welterweight", date:"2013-03-16", event:"UFC 158", winner:"Georges St-Pierre", loser:"Nick Diaz", type:"defense"},
{division:"Welterweight", date:"2013-11-16", event:"UFC 167", winner:"Georges St-Pierre", loser:"Johny Hendricks", type:"defense"},
{division:"Welterweight", date:"2014-03-15", event:"UFC 171", winner:"Johny Hendricks", loser:"Robbie Lawler", type:"change"},
{division:"Welterweight", date:"2014-12-06", event:"UFC 181", winner:"Robbie Lawler", loser:"Johny Hendricks", type:"change"},
{division:"Welterweight", date:"2015-07-11", event:"UFC 189", winner:"Robbie Lawler", loser:"Rory MacDonald", type:"defense"},
{division:"Welterweight", date:"2016-01-02", event:"UFC 195", winner:"Robbie Lawler", loser:"Carlos Condit", type:"defense"},
{division:"Welterweight", date:"2016-07-30", event:"UFC 201", winner:"Tyron Woodley", loser:"Robbie Lawler", type:"change"},
{division:"Welterweight", date:"2016-11-12", event:"UFC 205", winner:"Tyron Woodley", loser:"Stephen Thompson", type:"draw"},
{division:"Welterweight", date:"2017-03-04", event:"UFC 209", winner:"Tyron Woodley", loser:"Stephen Thompson", type:"defense"},
{division:"Welterweight", date:"2017-07-29", event:"UFC 214", winner:"Tyron Woodley", loser:"Demian Maia", type:"defense"},
{division:"Welterweight", date:"2018-06-09", event:"UFC 225", winner:"Colby Covington", loser:"Rafael dos Anjos", type:"interim"},
{division:"Welterweight", date:"2018-09-08", event:"UFC 228", winner:"Tyron Woodley", loser:"Darren Till", type:"defense"},
{division:"Welterweight", date:"2019-03-02", event:"UFC 235", winner:"Kamaru Usman", loser:"Tyron Woodley", type:"change"},
{division:"Welterweight", date:"2019-12-14", event:"UFC 245", winner:"Kamaru Usman", loser:"Colby Covington", type:"defense"},
{division:"Welterweight", date:"2020-07-11", event:"UFC 251", winner:"Kamaru Usman", loser:"Jorge Masvidal", type:"defense"},
{division:"Welterweight", date:"2021-02-13", event:"UFC 258", winner:"Kamaru Usman", loser:"Gilbert Burns", type:"defense"},
{division:"Welterweight", date:"2021-04-24", event:"UFC 261", winner:"Kamaru Usman", loser:"Jorge Masvidal", type:"defense"},
{division:"Welterweight", date:"2021-11-06", event:"UFC 268", winner:"Kamaru Usman", loser:"Colby Covington", type:"defense"},
{division:"Welterweight", date:"2022-08-20", event:"UFC 278", winner:"Leon Edwards", loser:"Kamaru Usman", type:"change"},
{division:"Welterweight", date:"2023-03-18", event:"UFC 286", winner:"Leon Edwards", loser:"Kamaru Usman", type:"defense"},
{division:"Welterweight", date:"2023-12-16", event:"UFC 296", winner:"Leon Edwards", loser:"Colby Covington", type:"defense"},
{division:"Welterweight", date:"2024-07-27", event:"UFC 304", winner:"Belal Muhammad", loser:"Leon Edwards", type:"change"},
{division:"Welterweight", date:"2025-05-10", event:"UFC 315", winner:"Jack Della Maddalena", loser:"Belal Muhammad", type:"change"},
{division:"Welterweight", date:"2025-11-15", event:"UFC 322", winner:"Islam Makhachev", loser:"Jack Della Maddalena", type:"change"},

// ===== LIGHTWEIGHT =====
{division:"Lightweight", date:"2001-02-23", event:"UFC 30", winner:"Jens Pulver", loser:"Caol Uno", type:"change"},
{division:"Lightweight", date:"2001-09-28", event:"UFC 33", winner:"Jens Pulver", loser:"Dennis Hallman", type:"defense"},
{division:"Lightweight", date:"2002-01-11", event:"UFC 35", winner:"Jens Pulver", loser:"B.J. Penn", type:"defense"},
{division:"Lightweight", date:"2003-02-28", event:"UFC 41", winner:"B.J. Penn", loser:"Caol Uno", type:"draw"},
{division:"Lightweight", date:"2006-10-14", event:"UFC 64", winner:"Sean Sherk", loser:"Kenny Florian", type:"change"},
{division:"Lightweight", date:"2007-07-07", event:"UFC 73", winner:"Sean Sherk", loser:"Hermes França", type:"defense"},
{division:"Lightweight", date:"2008-01-19", event:"UFC 80", winner:"B.J. Penn", loser:"Joe Stevenson", type:"change"},
{division:"Lightweight", date:"2008-05-24", event:"UFC 84", winner:"B.J. Penn", loser:"Sean Sherk", type:"defense"},
{division:"Lightweight", date:"2009-08-08", event:"UFC 101", winner:"B.J. Penn", loser:"Kenny Florian", type:"defense"},
{division:"Lightweight", date:"2009-12-12", event:"UFC 107", winner:"B.J. Penn", loser:"Diego Sanchez", type:"defense"},
{division:"Lightweight", date:"2010-04-10", event:"UFC 112", winner:"Frankie Edgar", loser:"B.J. Penn", type:"change"},
{division:"Lightweight", date:"2010-08-28", event:"UFC 118", winner:"Frankie Edgar", loser:"B.J. Penn", type:"defense"},
{division:"Lightweight", date:"2011-01-01", event:"UFC 125", winner:"Frankie Edgar", loser:"Gray Maynard", type:"draw"},
{division:"Lightweight", date:"2011-10-08", event:"UFC 136", winner:"Frankie Edgar", loser:"Gray Maynard", type:"defense"},
{division:"Lightweight", date:"2012-02-26", event:"UFC 144", winner:"Benson Henderson", loser:"Frankie Edgar", type:"change"},
{division:"Lightweight", date:"2012-08-11", event:"UFC 150", winner:"Benson Henderson", loser:"Frankie Edgar", type:"defense"},
{division:"Lightweight", date:"2012-12-08", event:"UFC on Fox: Henderson vs. Diaz", winner:"Benson Henderson", loser:"Nate Diaz", type:"defense"},
{division:"Lightweight", date:"2013-04-20", event:"UFC on Fox: Henderson vs. Melendez", winner:"Benson Henderson", loser:"Gilbert Melendez", type:"defense"},
{division:"Lightweight", date:"2013-08-31", event:"UFC 164", winner:"Anthony Pettis", loser:"Benson Henderson", type:"change"},
{division:"Lightweight", date:"2014-12-06", event:"UFC 181", winner:"Anthony Pettis", loser:"Gilbert Melendez", type:"defense"},
{division:"Lightweight", date:"2015-03-14", event:"UFC 185", winner:"Rafael dos Anjos", loser:"Anthony Pettis", type:"change"},
{division:"Lightweight", date:"2015-12-19", event:"UFC on Fox: dos Anjos vs. Cowboy 2", winner:"Rafael dos Anjos", loser:"Donald Cerrone", type:"defense"},
{division:"Lightweight", date:"2016-07-07", event:"UFC Fight Night: dos Anjos vs. Alvarez", winner:"Eddie Alvarez", loser:"Rafael dos Anjos", type:"change"},
{division:"Lightweight", date:"2016-11-12", event:"UFC 205", winner:"Conor McGregor", loser:"Eddie Alvarez", type:"change"},
{division:"Lightweight", date:"2017-10-07", event:"UFC 216", winner:"Tony Ferguson", loser:"Kevin Lee", type:"interim"},
{division:"Lightweight", date:"2018-04-07", event:"UFC 223", winner:"Khabib Nurmagomedov", loser:"Al Iaquinta", type:"change"},
{division:"Lightweight", date:"2018-10-06", event:"UFC 229", winner:"Khabib Nurmagomedov", loser:"Conor McGregor", type:"defense"},
{division:"Lightweight", date:"2019-04-13", event:"UFC 236", winner:"Dustin Poirier", loser:"Max Holloway", type:"interim"},
{division:"Lightweight", date:"2019-09-07", event:"UFC 242", winner:"Khabib Nurmagomedov", loser:"Dustin Poirier", type:"defense"},
{division:"Lightweight", date:"2020-05-09", event:"UFC 249", winner:"Justin Gaethje", loser:"Tony Ferguson", type:"interim"},
{division:"Lightweight", date:"2020-10-24", event:"UFC 254", winner:"Khabib Nurmagomedov", loser:"Justin Gaethje", type:"defense"},
{division:"Lightweight", date:"2021-05-15", event:"UFC 262", winner:"Charles Oliveira", loser:"Michael Chandler", type:"change"},
{division:"Lightweight", date:"2021-12-11", event:"UFC 269", winner:"Charles Oliveira", loser:"Dustin Poirier", type:"defense"},
{division:"Lightweight", date:"2022-10-22", event:"UFC 280", winner:"Islam Makhachev", loser:"Charles Oliveira", type:"change"},
{division:"Lightweight", date:"2023-02-12", event:"UFC 284", winner:"Islam Makhachev", loser:"Alexander Volkanovski", type:"defense"},
{division:"Lightweight", date:"2023-10-21", event:"UFC 294", winner:"Islam Makhachev", loser:"Alexander Volkanovski", type:"defense"},
{division:"Lightweight", date:"2024-06-01", event:"UFC 302", winner:"Islam Makhachev", loser:"Dustin Poirier", type:"defense"},
{division:"Lightweight", date:"2025-01-18", event:"UFC 311", winner:"Islam Makhachev", loser:"Renato Moicano", type:"defense"},
{division:"Lightweight", date:"2025-06-28", event:"UFC 317", winner:"Ilia Topuria", loser:"Charles Oliveira", type:"change"},
{division:"Lightweight", date:"2026-01-24", event:"UFC 324", winner:"Justin Gaethje", loser:"Paddy Pimblett", type:"interim"},
{division:"Lightweight", date:"2026-06-14", event:"UFC Freedom 250 (White House)", winner:"Justin Gaethje", loser:"Ilia Topuria", type:"change"},

// ===== FEATHERWEIGHT =====
{division:"Featherweight", date:"2010-11-20", event:"UFC 123", winner:"José Aldo", loser:"—", type:"promoted"},
{division:"Featherweight", date:"2011-04-30", event:"UFC 129", winner:"José Aldo", loser:"Mark Hominick", type:"defense"},
{division:"Featherweight", date:"2011-10-08", event:"UFC 136", winner:"José Aldo", loser:"Kenny Florian", type:"defense"},
{division:"Featherweight", date:"2012-01-14", event:"UFC 142", winner:"José Aldo", loser:"Chad Mendes", type:"defense"},
{division:"Featherweight", date:"2013-02-02", event:"UFC 156", winner:"José Aldo", loser:"Frankie Edgar", type:"defense"},
{division:"Featherweight", date:"2013-08-03", event:"UFC 163", winner:"José Aldo", loser:"Jung Chan-sung", type:"defense"},
{division:"Featherweight", date:"2014-02-01", event:"UFC 169", winner:"José Aldo", loser:"Ricardo Lamas", type:"defense"},
{division:"Featherweight", date:"2014-10-25", event:"UFC 179", winner:"José Aldo", loser:"Chad Mendes", type:"defense"},
{division:"Featherweight", date:"2015-07-11", event:"UFC 189", winner:"Conor McGregor", loser:"Chad Mendes", type:"interim"},
{division:"Featherweight", date:"2015-12-12", event:"UFC 194", winner:"Conor McGregor", loser:"José Aldo", type:"change"},
{division:"Featherweight", date:"2016-07-09", event:"UFC 200", winner:"José Aldo", loser:"Frankie Edgar", type:"interim"},
{division:"Featherweight", date:"2016-11-26", event:"—", winner:"José Aldo", loser:"Conor McGregor", type:"promoted"},
{division:"Featherweight", date:"2016-12-10", event:"UFC 206", winner:"Max Holloway", loser:"Anthony Pettis", type:"interim"},
{division:"Featherweight", date:"2017-06-03", event:"UFC 212", winner:"Max Holloway", loser:"José Aldo", type:"change"},
{division:"Featherweight", date:"2017-12-02", event:"UFC 218", winner:"Max Holloway", loser:"José Aldo", type:"defense"},
{division:"Featherweight", date:"2018-12-08", event:"UFC 231", winner:"Max Holloway", loser:"Brian Ortega", type:"defense"},
{division:"Featherweight", date:"2019-07-27", event:"UFC 240", winner:"Max Holloway", loser:"Frankie Edgar", type:"defense"},
{division:"Featherweight", date:"2019-12-14", event:"UFC 245", winner:"Alexander Volkanovski", loser:"Max Holloway", type:"change"},
{division:"Featherweight", date:"2020-07-12", event:"UFC 251", winner:"Alexander Volkanovski", loser:"Max Holloway", type:"defense"},
{division:"Featherweight", date:"2021-09-25", event:"UFC 266", winner:"Alexander Volkanovski", loser:"Brian Ortega", type:"defense"},
{division:"Featherweight", date:"2022-04-09", event:"UFC 273", winner:"Alexander Volkanovski", loser:"Jung Chan-sung", type:"defense"},
{division:"Featherweight", date:"2022-07-02", event:"UFC 276", winner:"Alexander Volkanovski", loser:"Max Holloway", type:"defense"},
{division:"Featherweight", date:"2023-02-12", event:"UFC 284", winner:"Yair Rodríguez", loser:"Josh Emmett", type:"interim"},
{division:"Featherweight", date:"2023-07-08", event:"UFC 290", winner:"Alexander Volkanovski", loser:"Yair Rodríguez", type:"defense"},
{division:"Featherweight", date:"2024-02-17", event:"UFC 298", winner:"Ilia Topuria", loser:"Alexander Volkanovski", type:"change"},
{division:"Featherweight", date:"2024-10-26", event:"UFC 308", winner:"Ilia Topuria", loser:"Max Holloway", type:"defense"},
{division:"Featherweight", date:"2025-04-12", event:"UFC 314", winner:"Alexander Volkanovski", loser:"Diego Lopes", type:"change"},
{division:"Featherweight", date:"2026-02-01", event:"UFC 325", winner:"Alexander Volkanovski", loser:"Diego Lopes", type:"defense"},

// ===== BANTAMWEIGHT =====
{division:"Bantamweight", date:"2010-12-16", event:"WEC 53", winner:"Dominick Cruz", loser:"Scott Jorgensen", type:"change"},
{division:"Bantamweight", date:"2011-07-02", event:"UFC 132", winner:"Dominick Cruz", loser:"Urijah Faber", type:"defense"},
{division:"Bantamweight", date:"2011-10-01", event:"UFC Live: Cruz vs. Johnson", winner:"Dominick Cruz", loser:"Demetrious Johnson", type:"defense"},
{division:"Bantamweight", date:"2012-07-21", event:"UFC 149", winner:"Renan Barão", loser:"Urijah Faber", type:"interim"},
{division:"Bantamweight", date:"2013-02-16", event:"UFC on Fuel TV: Barão vs. McDonald", winner:"Renan Barão", loser:"Michael McDonald", type:"defense"},
{division:"Bantamweight", date:"2013-09-21", event:"UFC 165", winner:"Renan Barão", loser:"Eddie Wineland", type:"defense"},
{division:"Bantamweight", date:"2014-01-06", event:"—", winner:"Renan Barão", loser:"Dominick Cruz", type:"promoted"},
{division:"Bantamweight", date:"2014-02-01", event:"UFC 169", winner:"Renan Barão", loser:"Urijah Faber", type:"defense"},
{division:"Bantamweight", date:"2014-05-24", event:"UFC 173", winner:"T.J. Dillashaw", loser:"Renan Barão", type:"change"},
{division:"Bantamweight", date:"2014-08-30", event:"UFC 177", winner:"T.J. Dillashaw", loser:"Joe Soto", type:"defense"},
{division:"Bantamweight", date:"2015-07-25", event:"UFC on Fox: Dillashaw vs. Barão 2", winner:"T.J. Dillashaw", loser:"Renan Barão", type:"defense"},
{division:"Bantamweight", date:"2016-01-17", event:"UFC Fight Night: Dillashaw vs. Cruz", winner:"Dominick Cruz", loser:"T.J. Dillashaw", type:"change"},
{division:"Bantamweight", date:"2016-06-04", event:"UFC 199", winner:"Dominick Cruz", loser:"Urijah Faber", type:"defense"},
{division:"Bantamweight", date:"2016-12-30", event:"UFC 207", winner:"Cody Garbrandt", loser:"Dominick Cruz", type:"change"},
{division:"Bantamweight", date:"2017-11-04", event:"UFC 217", winner:"T.J. Dillashaw", loser:"Cody Garbrandt", type:"change"},
{division:"Bantamweight", date:"2018-08-04", event:"UFC 227", winner:"T.J. Dillashaw", loser:"Cody Garbrandt", type:"defense"},
{division:"Bantamweight", date:"2019-06-08", event:"UFC 238", winner:"Henry Cejudo", loser:"Marlon Moraes", type:"change"},
{division:"Bantamweight", date:"2020-05-09", event:"UFC 249", winner:"Henry Cejudo", loser:"Dominick Cruz", type:"defense"},
{division:"Bantamweight", date:"2020-07-12", event:"UFC 251", winner:"Petr Yan", loser:"José Aldo", type:"change"},
{division:"Bantamweight", date:"2021-03-06", event:"UFC 259", winner:"Aljamain Sterling", loser:"Petr Yan", type:"change"},
{division:"Bantamweight", date:"2021-10-30", event:"UFC 267", winner:"Petr Yan", loser:"Cory Sandhagen", type:"interim"},
{division:"Bantamweight", date:"2022-04-09", event:"UFC 273", winner:"Aljamain Sterling", loser:"Petr Yan", type:"defense"},
{division:"Bantamweight", date:"2022-10-22", event:"UFC 280", winner:"Aljamain Sterling", loser:"T.J. Dillashaw", type:"defense"},
{division:"Bantamweight", date:"2023-05-06", event:"UFC 288", winner:"Aljamain Sterling", loser:"Henry Cejudo", type:"defense"},
{division:"Bantamweight", date:"2023-08-19", event:"UFC 292", winner:"Sean O'Malley", loser:"Aljamain Sterling", type:"change"},
{division:"Bantamweight", date:"2024-03-09", event:"UFC 299", winner:"Sean O'Malley", loser:"Marlon Vera", type:"defense"},
{division:"Bantamweight", date:"2024-09-14", event:"UFC 306", winner:"Merab Dvalishvili", loser:"Sean O'Malley", type:"change"},
{division:"Bantamweight", date:"2025-01-18", event:"UFC 311", winner:"Merab Dvalishvili", loser:"Umar Nurmagomedov", type:"defense"},
{division:"Bantamweight", date:"2025-06-07", event:"UFC 316", winner:"Merab Dvalishvili", loser:"Sean O'Malley", type:"defense"},
{division:"Bantamweight", date:"2025-10-04", event:"UFC 320", winner:"Merab Dvalishvili", loser:"Cory Sandhagen", type:"defense"},
{division:"Bantamweight", date:"2025-12-06", event:"UFC 323", winner:"Petr Yan", loser:"Merab Dvalishvili", type:"change"},

// ===== FLYWEIGHT =====
{division:"Flyweight", date:"2012-09-22", event:"UFC 152", winner:"Demetrious Johnson", loser:"Joseph Benavidez", type:"change"},
{division:"Flyweight", date:"2013-01-26", event:"UFC on Fox: Johnson vs. Dodson", winner:"Demetrious Johnson", loser:"John Dodson", type:"defense"},
{division:"Flyweight", date:"2013-07-27", event:"UFC on Fox: Johnson vs. Moraga", winner:"Demetrious Johnson", loser:"John Moraga", type:"defense"},
{division:"Flyweight", date:"2013-12-14", event:"UFC on Fox: Johnson vs. Benavidez 2", winner:"Demetrious Johnson", loser:"Joseph Benavidez", type:"defense"},
{division:"Flyweight", date:"2014-06-14", event:"UFC 174", winner:"Demetrious Johnson", loser:"Ali Bagautinov", type:"defense"},
{division:"Flyweight", date:"2014-09-27", event:"UFC 178", winner:"Demetrious Johnson", loser:"Chris Cariaso", type:"defense"},
{division:"Flyweight", date:"2015-04-25", event:"UFC 186", winner:"Demetrious Johnson", loser:"Kyoji Horiguchi", type:"defense"},
{division:"Flyweight", date:"2015-09-05", event:"UFC 191", winner:"Demetrious Johnson", loser:"John Dodson", type:"defense"},
{division:"Flyweight", date:"2016-04-23", event:"UFC 197", winner:"Demetrious Johnson", loser:"Henry Cejudo", type:"defense"},
{division:"Flyweight", date:"2016-12-03", event:"The Ultimate Fighter 24 Finale", winner:"Demetrious Johnson", loser:"Tim Elliott", type:"defense"},
{division:"Flyweight", date:"2017-04-15", event:"UFC on Fox: Johnson vs. Reis", winner:"Demetrious Johnson", loser:"Wilson Reis", type:"defense"},
{division:"Flyweight", date:"2017-10-07", event:"UFC 216", winner:"Demetrious Johnson", loser:"Ray Borg", type:"defense"},
{division:"Flyweight", date:"2018-08-04", event:"UFC 227", winner:"Henry Cejudo", loser:"Demetrious Johnson", type:"change"},
{division:"Flyweight", date:"2019-01-19", event:"UFC Fight Night: Cejudo vs. Dillashaw", winner:"Henry Cejudo", loser:"T.J. Dillashaw", type:"defense"},
{division:"Flyweight", date:"2020-07-19", event:"UFC Fight Night: Figueiredo vs. Benavidez 2", winner:"Deiveson Figueiredo", loser:"Joseph Benavidez", type:"change"},
{division:"Flyweight", date:"2020-11-21", event:"UFC 255", winner:"Deiveson Figueiredo", loser:"Alex Perez", type:"defense"},
{division:"Flyweight", date:"2020-12-12", event:"UFC 256", winner:"Deiveson Figueiredo", loser:"Brandon Moreno", type:"draw"},
{division:"Flyweight", date:"2021-06-12", event:"UFC 263", winner:"Brandon Moreno", loser:"Deiveson Figueiredo", type:"change"},
{division:"Flyweight", date:"2022-01-22", event:"UFC 270", winner:"Deiveson Figueiredo", loser:"Brandon Moreno", type:"change"},
{division:"Flyweight", date:"2022-07-30", event:"UFC 277", winner:"Brandon Moreno", loser:"Kai Kara-France", type:"interim"},
{division:"Flyweight", date:"2023-01-21", event:"UFC 283", winner:"Brandon Moreno", loser:"Deiveson Figueiredo", type:"change"},
{division:"Flyweight", date:"2023-07-08", event:"UFC 290", winner:"Alexandre Pantoja", loser:"Brandon Moreno", type:"change"},
{division:"Flyweight", date:"2023-12-16", event:"UFC 296", winner:"Alexandre Pantoja", loser:"Brandon Royval", type:"defense"},
{division:"Flyweight", date:"2024-05-04", event:"UFC 301", winner:"Alexandre Pantoja", loser:"Steve Erceg", type:"defense"},
{division:"Flyweight", date:"2024-12-07", event:"UFC 310", winner:"Alexandre Pantoja", loser:"Kai Asakura", type:"defense"},
{division:"Flyweight", date:"2025-06-28", event:"UFC 317", winner:"Alexandre Pantoja", loser:"Kai Kara-France", type:"defense"},
{division:"Flyweight", date:"2025-12-06", event:"UFC 323", winner:"Joshua Van", loser:"Alexandre Pantoja", type:"change"},
{division:"Flyweight", date:"2026-05-09", event:"UFC 328", winner:"Joshua Van", loser:"Tatsuro Taira", type:"defense"},

// ===== WOMEN'S BANTAMWEIGHT =====
{division:"Women's Bantamweight", date:"2012-12-06", event:"UFC on Fox: Henderson vs. Diaz", winner:"Ronda Rousey", loser:"—", type:"promoted"},
{division:"Women's Bantamweight", date:"2013-02-23", event:"UFC 157", winner:"Ronda Rousey", loser:"Liz Carmouche", type:"defense"},
{division:"Women's Bantamweight", date:"2013-12-28", event:"UFC 168", winner:"Ronda Rousey", loser:"Miesha Tate", type:"defense"},
{division:"Women's Bantamweight", date:"2014-02-22", event:"UFC 170", winner:"Ronda Rousey", loser:"Sara McMann", type:"defense"},
{division:"Women's Bantamweight", date:"2014-07-05", event:"UFC 175", winner:"Ronda Rousey", loser:"Alexis Davis", type:"defense"},
{division:"Women's Bantamweight", date:"2015-02-28", event:"UFC 184", winner:"Ronda Rousey", loser:"Cat Zingano", type:"defense"},
{division:"Women's Bantamweight", date:"2015-08-01", event:"UFC 190", winner:"Ronda Rousey", loser:"Bethe Correia", type:"defense"},
{division:"Women's Bantamweight", date:"2015-11-15", event:"UFC 193", winner:"Holly Holm", loser:"Ronda Rousey", type:"change"},
{division:"Women's Bantamweight", date:"2016-03-05", event:"UFC 196", winner:"Miesha Tate", loser:"Holly Holm", type:"change"},
{division:"Women's Bantamweight", date:"2016-07-09", event:"UFC 200", winner:"Amanda Nunes", loser:"Miesha Tate", type:"change"},
{division:"Women's Bantamweight", date:"2016-12-30", event:"UFC 207", winner:"Amanda Nunes", loser:"Ronda Rousey", type:"defense"},
{division:"Women's Bantamweight", date:"2017-09-09", event:"UFC 215", winner:"Amanda Nunes", loser:"Valentina Shevchenko", type:"defense"},
{division:"Women's Bantamweight", date:"2018-05-12", event:"UFC 224", winner:"Amanda Nunes", loser:"Raquel Pennington", type:"defense"},
{division:"Women's Bantamweight", date:"2019-07-06", event:"UFC 239", winner:"Amanda Nunes", loser:"Holly Holm", type:"defense"},
{division:"Women's Bantamweight", date:"2019-12-14", event:"UFC 245", winner:"Amanda Nunes", loser:"Germaine de Randamie", type:"defense"},
{division:"Women's Bantamweight", date:"2021-12-11", event:"UFC 269", winner:"Julianna Peña", loser:"Amanda Nunes", type:"change"},
{division:"Women's Bantamweight", date:"2022-07-30", event:"UFC 277", winner:"Amanda Nunes", loser:"Julianna Peña", type:"change"},
{division:"Women's Bantamweight", date:"2023-06-10", event:"UFC 289", winner:"Amanda Nunes", loser:"Irene Aldana", type:"defense"},
{division:"Women's Bantamweight", date:"2024-01-20", event:"UFC 297", winner:"Raquel Pennington", loser:"Mayra Bueno Silva", type:"change"},
{division:"Women's Bantamweight", date:"2024-10-05", event:"UFC 307", winner:"Julianna Peña", loser:"Raquel Pennington", type:"change"},
{division:"Women's Bantamweight", date:"2025-06-07", event:"UFC 316", winner:"Kayla Harrison", loser:"Julianna Peña", type:"change"},
{division:"Women's Bantamweight", date:"2026-01-24", event:"UFC 324", winner:"Kayla Harrison", loser:"Amanda Nunes", type:"defense"},

// ===== WOMEN'S FLYWEIGHT =====
{division:"Women's Flyweight", date:"2017-12-01", event:"TUF 26 Finale", winner:"Nicco Montaño", loser:"Roxanne Modafferi", type:"change"},
{division:"Women's Flyweight", date:"2018-12-08", event:"UFC 231", winner:"Valentina Shevchenko", loser:"Joanna Jędrzejczyk", type:"change"},
{division:"Women's Flyweight", date:"2019-06-08", event:"UFC 238", winner:"Valentina Shevchenko", loser:"Jessica Eye", type:"defense"},
{division:"Women's Flyweight", date:"2019-08-10", event:"UFC Fight Night: Shevchenko vs. Carmouche 2", winner:"Valentina Shevchenko", loser:"Liz Carmouche", type:"defense"},
{division:"Women's Flyweight", date:"2020-02-08", event:"UFC 247", winner:"Valentina Shevchenko", loser:"Katlyn Chookagian", type:"defense"},
{division:"Women's Flyweight", date:"2020-11-21", event:"UFC 255", winner:"Valentina Shevchenko", loser:"Jennifer Maia", type:"defense"},
{division:"Women's Flyweight", date:"2021-04-24", event:"UFC 261", winner:"Valentina Shevchenko", loser:"Jéssica Andrade", type:"defense"},
{division:"Women's Flyweight", date:"2021-09-25", event:"UFC 266", winner:"Valentina Shevchenko", loser:"Lauren Murphy", type:"defense"},
{division:"Women's Flyweight", date:"2022-06-12", event:"UFC 275", winner:"Valentina Shevchenko", loser:"Taila Santos", type:"defense"},
{division:"Women's Flyweight", date:"2023-03-04", event:"UFC 285", winner:"Alexa Grasso", loser:"Valentina Shevchenko", type:"change"},
{division:"Women's Flyweight", date:"2023-09-16", event:"UFC Fight Night: Grasso vs. Shevchenko 2", winner:"Alexa Grasso", loser:"Valentina Shevchenko", type:"draw"},
{division:"Women's Flyweight", date:"2024-09-14", event:"UFC 306", winner:"Valentina Shevchenko", loser:"Alexa Grasso", type:"change"},
{division:"Women's Flyweight", date:"2025-05-10", event:"UFC 315", winner:"Valentina Shevchenko", loser:"Manon Fiorot", type:"defense"},
{division:"Women's Flyweight", date:"2025-11-15", event:"UFC 322", winner:"Valentina Shevchenko", loser:"Zhang Weili", type:"defense"},

// ===== WOMEN'S STRAWWEIGHT =====
{division:"Women's Strawweight", date:"2014-12-12", event:"TUF 20 Finale", winner:"Carla Esparza", loser:"Rose Namajunas", type:"change"},
{division:"Women's Strawweight", date:"2015-03-14", event:"UFC 185", winner:"Joanna Jędrzejczyk", loser:"Carla Esparza", type:"change"},
{division:"Women's Strawweight", date:"2015-06-20", event:"UFC Fight Night: Jędrzejczyk vs. Penne", winner:"Joanna Jędrzejczyk", loser:"Jessica Penne", type:"defense"},
{division:"Women's Strawweight", date:"2015-11-15", event:"UFC 193", winner:"Joanna Jędrzejczyk", loser:"Valérie Létourneau", type:"defense"},
{division:"Women's Strawweight", date:"2016-07-08", event:"TUF 23 Finale", winner:"Joanna Jędrzejczyk", loser:"Cláudia Gadelha", type:"defense"},
{division:"Women's Strawweight", date:"2016-11-12", event:"UFC 205", winner:"Joanna Jędrzejczyk", loser:"Karolina Kowalkiewicz", type:"defense"},
{division:"Women's Strawweight", date:"2017-05-13", event:"UFC 211", winner:"Joanna Jędrzejczyk", loser:"Jéssica Andrade", type:"defense"},
{division:"Women's Strawweight", date:"2017-11-04", event:"UFC 217", winner:"Rose Namajunas", loser:"Joanna Jędrzejczyk", type:"change"},
{division:"Women's Strawweight", date:"2018-04-07", event:"UFC 223", winner:"Rose Namajunas", loser:"Joanna Jędrzejczyk", type:"defense"},
{division:"Women's Strawweight", date:"2019-05-11", event:"UFC 237", winner:"Jéssica Andrade", loser:"Rose Namajunas", type:"change"},
{division:"Women's Strawweight", date:"2019-08-31", event:"UFC Fight Night: Andrade vs. Zhang", winner:"Zhang Weili", loser:"Jéssica Andrade", type:"change"},
{division:"Women's Strawweight", date:"2020-03-07", event:"UFC 248", winner:"Zhang Weili", loser:"Joanna Jędrzejczyk", type:"defense"},
{division:"Women's Strawweight", date:"2021-04-24", event:"UFC 261", winner:"Rose Namajunas", loser:"Zhang Weili", type:"change"},
{division:"Women's Strawweight", date:"2021-11-06", event:"UFC 268", winner:"Rose Namajunas", loser:"Zhang Weili", type:"defense"},
{division:"Women's Strawweight", date:"2022-05-07", event:"UFC 274", winner:"Carla Esparza", loser:"Rose Namajunas", type:"change"},
{division:"Women's Strawweight", date:"2022-11-12", event:"UFC 281", winner:"Zhang Weili", loser:"Carla Esparza", type:"change"},
{division:"Women's Strawweight", date:"2023-08-19", event:"UFC 292", winner:"Zhang Weili", loser:"Amanda Lemos", type:"defense"},
{division:"Women's Strawweight", date:"2024-04-13", event:"UFC 300", winner:"Zhang Weili", loser:"Yan Xiaonan", type:"defense"},
{division:"Women's Strawweight", date:"2025-02-09", event:"UFC 312", winner:"Zhang Weili", loser:"Tatiana Suarez", type:"defense"},
{division:"Women's Strawweight", date:"2025-10-25", event:"UFC 321", winner:"Mackenzie Dern", loser:"Virna Jandiroba", type:"change"},

// ===== WOMEN'S FEATHERWEIGHT (discontinued) =====
{division:"Women's Featherweight", date:"2017-02-11", event:"UFC 208", winner:"Germaine de Randamie", loser:"Holly Holm", type:"change"},
{division:"Women's Featherweight", date:"2017-07-29", event:"UFC 214", winner:"Cris Cyborg", loser:"Tonya Evinger", type:"change"},
{division:"Women's Featherweight", date:"2017-12-30", event:"UFC 219", winner:"Cris Cyborg", loser:"Holly Holm", type:"defense"},
{division:"Women's Featherweight", date:"2018-03-03", event:"UFC 222", winner:"Cris Cyborg", loser:"Yana Kunitskaya", type:"defense"},
{division:"Women's Featherweight", date:"2018-12-29", event:"UFC 232", winner:"Amanda Nunes", loser:"Cris Cyborg", type:"change"},
{division:"Women's Featherweight", date:"2020-06-06", event:"UFC 250", winner:"Amanda Nunes", loser:"Felicia Spencer", type:"defense"},
{division:"Women's Featherweight", date:"2021-03-06", event:"UFC 259", winner:"Amanda Nunes", loser:"Megan Anderson", type:"defense"},

// ===== BMF TITLE (unofficial, cross-division) =====
{division:"BMF", date:"2019-11-02", event:"UFC 244", winner:"Jorge Masvidal", loser:"Nate Diaz", type:"change"},
{division:"BMF", date:"2023-07-29", event:"UFC 291", winner:"Justin Gaethje", loser:"Dustin Poirier", type:"change"},
{division:"BMF", date:"2024-04-13", event:"UFC 300", winner:"Max Holloway", loser:"Justin Gaethje", type:"change"},
{division:"BMF", date:"2025-07-19", event:"UFC 318", winner:"Max Holloway", loser:"Dustin Poirier", type:"defense"},
{division:"BMF", date:"2026-03-07", event:"UFC 326", winner:"Charles Oliveira", loser:"Max Holloway", type:"change"},

// ===== HISTORICAL ROOT: UFC OPENWEIGHT TITLE (pre weight-class era, distinct from the UFC 1-11 single-night tournaments) =====
{division:"Openweight", date:"1995-07-14", event:"UFC 6", winner:"Ken Shamrock", loser:"Dan Severn", type:"change"},
{division:"Openweight", date:"1995-09-08", event:"UFC 7", winner:"Ken Shamrock", loser:"Oleg Taktarov", type:"draw"},
{division:"Openweight", date:"1996-02-16", event:"UFC 8", winner:"Ken Shamrock", loser:"Kimo Leopoldo", type:"defense"},
{division:"Openweight", date:"1996-05-17", event:"UFC 9", winner:"Dan Severn", loser:"Ken Shamrock", type:"change"},
];

const DIVISION_COLORS = {
  "Heavyweight": "#ff6b6b",
  "Light Heavyweight": "#ffa94d",
  "Middleweight": "#ffd43b",
  "Welterweight": "#94d82d",
  "Lightweight": "#20c997",
  "Featherweight": "#22b8cf",
  "Bantamweight": "#4dabf7",
  "Flyweight": "#748ffc",
  "Women's Bantamweight": "#da77f2",
  "Women's Flyweight": "#f783ac",
  "Women's Strawweight": "#e64980",
  "Women's Featherweight": "#fab005",
  "BMF": "#adb5bd",
  "Openweight": "#868e96"
};

const DIVISION_ORDER = ["Heavyweight","Light Heavyweight","Middleweight","Welterweight","Lightweight","Featherweight","Bantamweight","Flyweight","Women's Bantamweight","Women's Flyweight","Women's Strawweight","Women's Featherweight","BMF","Openweight"];
